include colors.conf

font_family      JetBrainsMono Nerd Font Mono
font_size        18.0
cursor_blink_interval 0
window_padding_width  15
background_opacity    0.95
dynamic_background_opacity yes
confirm_os_window_close 0

scrollback_lines 10000
copy_on_select   clipboard
strip_trailing_spaces smart

mouse_hide_wait 3.0
url_style      curly
open_url_with  default

enabled_layouts splits,stack,tall,fat


map alt+v        launch --location=vsplit --cwd=current
map alt+s        launch --location=hsplit --cwd=current
map alt+enter    launch --location=split --cwd=current
map alt+w        close_window

map alt+h        neighboring_window left
map alt+l        neighboring_window right
map alt+k        neighboring_window up
map alt+j        neighboring_window down

map alt+f        toggle_layout stack

map alt+r>h      resize_window narrower 3
map alt+r>l      resize_window wider 3
map alt+r>k      resize_window taller 3
map alt+r>j      resize_window shorter 3
map alt+r>r      resize_window reset

map alt+1        goto_tab 1
map alt+2        goto_tab 2
map alt+t        new_tab
map alt+q        close_tab

map alt+/        launch --type=overlay --stdin-source=@screen_scrollback fzf

map alt+u        kitten hints

map alt+p        kitten hints --type path --program -
